/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cTCzYqWgaP9vpqpv3zu3qB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsp7JuQLvvXa8N } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: P7JuQLvvXA8n/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsp7JuQLvvXa8N
});
