/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cTCzYqWgaP9vpqpv3zu3qB

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: cTCzYqWgaP9vpqpv3zu3qB/projectModule
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : "#shadowBox {\n  background-color: rgb(0, 0, 0);\n  /* Fallback color */\n  background-color: rgba(0, 0, 0, 0.);\n  /* Black w/opacity/see-through */\n  border: 3px solid;\n}\n\n.rainbow {\n  text-align: unset;\n  font-size: 64pt;\n  font-family: 'jetbrains mono';\n  letter-spacing: unset;\n  animation: colorRotate 8s linear 0s infinite;\n}\n\n.rainbow2 {\n  text-align: unset;\n  font-size: 36pt;\n  font-family: unset;\n  letter-spacing: unset;\n  animation: colorRotate 8s linear 0s infinite;\n}\n\n\n@keyframes colorRotate {\n  from {\n    color: #ff3070;\n  }\n  10% {\n    color: #FE96DE;\n  }\n  20% {\n    color: #9886ff;\n  }\n  40% {\n    color: rgb(118, 138, 255);\n  }\n  60% {\n    color: #9886ff;\n  }\n  80% {\n    color:#FE96DE;\n  }\n  100% {\n    color: #ff3070;\n  }\n}\n"
      }
    >
      {children}
    </EmbedCss>
  );
}
