/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cTCzYqWgaP9vpqpv3zu3qB
// Component: p7ZVmGxTNlEE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: cTCzYqWgaP9vpqpv3zu3qB/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: cTCzYqWgaP9vpqpv3zu3qB/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: cTCzYqWgaP9vpqpv3zu3qB/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: p7ZVmGxTNlEE/css

import MinecraftSvgIconsSvgIcon from "./icons/PlasmicIcon__MinecraftSvgIconsSvg"; // plasmic-import: HRR-pMXZUQfJ/icon
import MachineLearningIconSvgIcon from "./icons/PlasmicIcon__MachineLearningIconSvg"; // plasmic-import: _WYVaA7VYj75/icon
import ButterflyMonocolorSvgSvgIcon from "./icons/PlasmicIcon__ButterflyMonocolorSvgSvg"; // plasmic-import: G2TmnLRHy-1h/icon
import DrawingSvgVectors3SvgIcon from "./icons/PlasmicIcon__DrawingSvgVectors3Svg"; // plasmic-import: dojloyZS93dr/icon
import CodeSvgIconsSvgIcon from "./icons/PlasmicIcon__CodeSvgIconsSvg"; // plasmic-import: 2b-HVQBC04jO/icon

createPlasmicElementProxy;

export type PlasmicHeader__VariantMembers = {};
export type PlasmicHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  headerRoot?: Flex__<"div">;
  minecraftServer?: Flex__<"a"> & Partial<LinkProps>;
  ai?: Flex__<"a"> & Partial<LinkProps>;
  home?: Flex__<"a"> & Partial<LinkProps>;
  arts?: Flex__<"a"> & Partial<LinkProps>;
  code?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultHeaderProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"headerRoot"}
      data-plasmic-override={overrides.headerRoot}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.headerRoot
      )}
    >
      <PlasmicLink__
        data-plasmic-name={"minecraftServer"}
        data-plasmic-override={overrides.minecraftServer}
        className={classNames(
          projectcss.all,
          projectcss.a,
          sty.minecraftServer
        )}
        component={Link}
        href={`/mc`}
        platform={"nextjs"}
      >
        <MinecraftSvgIconsSvgIcon
          className={classNames(projectcss.all, sty.svg__vkthQ)}
          role={"img"}
        />
      </PlasmicLink__>
      <PlasmicLink__
        data-plasmic-name={"ai"}
        data-plasmic-override={overrides.ai}
        className={classNames(projectcss.all, projectcss.a, sty.ai)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <MachineLearningIconSvgIcon
          className={classNames(projectcss.all, sty.svg___33Zc1)}
          role={"img"}
        />
      </PlasmicLink__>
      <PlasmicLink__
        data-plasmic-name={"home"}
        data-plasmic-override={overrides.home}
        className={classNames(projectcss.all, projectcss.a, sty.home)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <ButterflyMonocolorSvgSvgIcon
          className={classNames(projectcss.all, sty.svg__b9SpU)}
          role={"img"}
        />
      </PlasmicLink__>
      <PlasmicLink__
        data-plasmic-name={"arts"}
        data-plasmic-override={overrides.arts}
        className={classNames(projectcss.all, projectcss.a, sty.arts)}
        component={Link}
        href={`/`}
        platform={"nextjs"}
      >
        <DrawingSvgVectors3SvgIcon
          className={classNames(projectcss.all, sty.svg__exM8I)}
          role={"img"}
        />
      </PlasmicLink__>
      <PlasmicLink__
        data-plasmic-name={"code"}
        data-plasmic-override={overrides.code}
        className={classNames(projectcss.all, projectcss.a, sty.code)}
        component={Link}
        href={`/projects`}
        platform={"nextjs"}
      >
        <CodeSvgIconsSvgIcon
          className={classNames(projectcss.all, sty.svg__f7Y0)}
          role={"img"}
        />
      </PlasmicLink__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  headerRoot: ["headerRoot", "minecraftServer", "ai", "home", "arts", "code"],
  minecraftServer: ["minecraftServer"],
  ai: ["ai"],
  home: ["home"],
  arts: ["arts"],
  code: ["code"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  headerRoot: "div";
  minecraftServer: "a";
  ai: "a";
  home: "a";
  arts: "a";
  code: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "headerRoot") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("headerRoot"),
  {
    // Helper components rendering sub-elements
    minecraftServer: makeNodeComponent("minecraftServer"),
    ai: makeNodeComponent("ai"),
    home: makeNodeComponent("home"),
    arts: makeNodeComponent("arts"),
    code: makeNodeComponent("code"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
