/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdk3mmCwk3GzhDjg1owJ7z

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rdk3mmCwk3GzhDjg1owJ7z/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: rdk3mmCwk3GzhDjg1owJ7z/projectcss

import plasmic_documentation_template_css from "../documentation_template/plasmic.module.css"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/projectcss
import plasmic_luailyhome_v_3_0_resources_css from "../luailyhome_v_3_0_resources/plasmic.module.css"; // plasmic-import: cTCzYqWgaP9vpqpv3zu3qB/projectcss

const data = {
  base: `${projectcss.plasmic_tokens} ${plasmic_documentation_template_css.plasmic_tokens} ${plasmic_luailyhome_v_3_0_resources_css.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
