/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdk3mmCwk3GzhDjg1owJ7z

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsozGxfu0JVsw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -OZGxfu0JVsw/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsozGxfu0JVsw
});
