/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdk3mmCwk3GzhDjg1owJ7z
// Component: Vsz5ok1OihHD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rdk3mmCwk3GzhDjg1owJ7z/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: rdk3mmCwk3GzhDjg1owJ7z/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: rdk3mmCwk3GzhDjg1owJ7z/projectcss
import sty from "./PlasmicRoot.module.css"; // plasmic-import: Vsz5ok1OihHD/css

import Warning20PxSvgrepoComSvgIcon from "../documentation_template/icons/PlasmicIcon__Warning20PxSvgrepoComSvg"; // plasmic-import: t3xlMnYJQ3N_/icon
import BlueskyLogoBlackSvgIcon from "../luailyhome_v_3_0_resources/icons/PlasmicIcon__BlueskyLogoBlackSvg"; // plasmic-import: 28HZnI5AGkYt/icon
import Twitter154SvgrepoCom1SvgIcon from "./icons/PlasmicIcon__Twitter154SvgrepoCom1Svg"; // plasmic-import: 9J3IvLmcdLEc/icon
import YouTubeVectorIconSvgIcon from "../luailyhome_v_3_0_resources/icons/PlasmicIcon__YouTubeVectorIconSvg"; // plasmic-import: R2bqW38sFmhv/icon
import GitLabSvgIconsSvgIcon from "../documentation_template/icons/PlasmicIcon__GitLabSvgIconsSvg"; // plasmic-import: 8VT4cyJhAMVS/icon

createPlasmicElementProxy;

export type PlasmicRoot__VariantMembers = {};
export type PlasmicRoot__VariantsArgs = {};
type VariantPropType = keyof PlasmicRoot__VariantsArgs;
export const PlasmicRoot__VariantProps = new Array<VariantPropType>();

export type PlasmicRoot__ArgsType = {};
type ArgPropType = keyof PlasmicRoot__ArgsType;
export const PlasmicRoot__ArgProps = new Array<ArgPropType>();

export type PlasmicRoot__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<"div">;
  portfolio?: Flex__<"section">;
  pfp?: Flex__<typeof PlasmicImg__>;
  bluesky?: Flex__<"a"> & Partial<LinkProps>;
  twitter?: Flex__<"a"> & Partial<LinkProps>;
  youTube?: Flex__<"a"> & Partial<LinkProps>;
  gitLab?: Flex__<"a"> & Partial<LinkProps>;
  footer?: Flex__<"section">;
};

export interface DefaultRootProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRoot__RenderFunc(props: {
  variants: PlasmicRoot__VariantsArgs;
  args: PlasmicRoot__ArgsType;
  overrides: PlasmicRoot__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicRoot.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicRoot.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicRoot.pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={PlasmicRoot.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicRoot.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={PlasmicRoot.pageMetadata.description}
        />

        <link rel="canonical" href={PlasmicRoot.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"navBar"}
          data-plasmic-override={overrides.navBar}
          className={classNames(projectcss.all, sty.navBar)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__es771)}>
            <Warning20PxSvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__jwuZj)}
              role={"img"}
            />

            <div className={classNames(projectcss.all, sty.freeBox__kWEpG)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u8JTb
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {"Warning: The main site will be changed to "}
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__bn3Jk
                      )}
                      component={Link}
                      href={"https://luaily.art"}
                      platform={"nextjs"}
                    >
                      {"luaily.art"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>
                    {
                      " starting Feburary 1st.\nThe transition period will end Feb 10th and on Feb 13th this site will stop working.\nStarting Feb 5th, to Feb 13th, luaily.site will auto-redirect to luaily.art."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___55Vj2
                )}
                component={Link}
                href={"https://www.plasmic.app/"}
                platform={"nextjs"}
              >
                {"go to luaily.art now -->"}
              </PlasmicLink__>
            </div>
          </div>
        </div>
        <section
          data-plasmic-name={"portfolio"}
          data-plasmic-override={overrides.portfolio}
          className={classNames(projectcss.all, sty.portfolio)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__rVxzp)}>
            <div className={classNames(projectcss.all, sty.freeBox__v1KB2)}>
              <PlasmicImg__
                data-plasmic-name={"pfp"}
                data-plasmic-override={overrides.pfp}
                alt={""}
                className={classNames(sty.pfp)}
                displayHeight={"120px"}
                displayMaxHeight={"160px"}
                displayMaxWidth={"160px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"120px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/luailyhome_v_3_0_resources/images/_170540I23169971498Png.png",
                  fullWidth: 860,
                  fullHeight: 1724,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mnwq
                )}
              >
                {"luaily"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__joAvS
                )}
              >
                {""}
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vq7TZ
              )}
            >
              {
                "hello! i'm luaily (pronounced: lo-allie), a below average american high school art student, graphic designer, game and software developer and animator. i excel in procrastination."
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__h3PhB)}>
              <div className={classNames(projectcss.all, sty.freeBox__awAIf)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__tdO0F
                  )}
                  component={Link}
                  href={"mailto:luailyart+hello@proton.me"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"luailyart+hello@proton.me"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__loA9X
                  )}
                  component={Link}
                  href={"https://solo.to/luaily"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"solo.to/luaily"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__sa2B7)}>
                <PlasmicLink__
                  data-plasmic-name={"bluesky"}
                  data-plasmic-override={overrides.bluesky}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.bluesky
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  <BlueskyLogoBlackSvgIcon
                    className={classNames(projectcss.all, sty.svg__wo4D6)}
                    role={"img"}
                  />
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"twitter"}
                  data-plasmic-override={overrides.twitter}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.twitter
                  )}
                  component={Link}
                  href={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "https://x.com/strwberrifieldz"
                      : undefined
                  }
                  platform={"nextjs"}
                  target={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "_blank"
                      : undefined
                  }
                >
                  <Twitter154SvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__q59Ab)}
                    role={"img"}
                  />
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"youTube"}
                  data-plasmic-override={overrides.youTube}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.youTube
                  )}
                  component={Link}
                  href={"https://youtube.com/@pieboi"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <YouTubeVectorIconSvgIcon
                    className={classNames(projectcss.all, sty.svg___3JXk1)}
                    role={"img"}
                  />
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"gitLab"}
                  data-plasmic-override={overrides.gitLab}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.gitLab
                  )}
                  component={Link}
                  href={"https://gitlab.com/luaily"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <GitLabSvgIconsSvgIcon
                    className={classNames(projectcss.all, sty.svg__z5Cuv)}
                    role={"img"}
                  />
                </PlasmicLink__>
              </div>
            </div>
          </div>
        </section>
        <section
          data-plasmic-name={"footer"}
          data-plasmic-override={overrides.footer}
          className={classNames(projectcss.all, sty.footer)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__n6Faf
            )}
          >
            <React.Fragment>
              <React.Fragment>{"Designed by "}</React.Fragment>
              {
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__fof
                  )}
                  component={Link}
                  href={"/"}
                  platform={"nextjs"}
                >
                  {"luaily"}
                </PlasmicLink__>
              }
              <React.Fragment>{" <3 | site: "}</React.Fragment>
              {
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__dNgF6
                  )}
                  component={Link}
                  href={"/site-versions"}
                  platform={"nextjs"}
                >
                  {"v3.0-Sakura"}
                </PlasmicLink__>
              }
              <React.Fragment>
                {
                  "\nCopyright \u00a9 2026 Luaily Productions. All Rights Reserved."
                }
              </React.Fragment>
            </React.Fragment>
          </div>
        </section>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "portfolio",
    "pfp",
    "bluesky",
    "twitter",
    "youTube",
    "gitLab",
    "footer"
  ],
  navBar: ["navBar"],
  portfolio: ["portfolio", "pfp", "bluesky", "twitter", "youTube", "gitLab"],
  pfp: ["pfp"],
  bluesky: ["bluesky"],
  twitter: ["twitter"],
  youTube: ["youTube"],
  gitLab: ["gitLab"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "div";
  portfolio: "section";
  pfp: typeof PlasmicImg__;
  bluesky: "a";
  twitter: "a";
  youTube: "a";
  gitLab: "a";
  footer: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRoot__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRoot__VariantsArgs;
    args?: PlasmicRoot__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicRoot__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicRoot__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRoot__ArgProps,
          internalVariantPropNames: PlasmicRoot__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRoot__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRoot";
  } else {
    func.displayName = `PlasmicRoot.${nodeName}`;
  }
  return func;
}

export const PlasmicRoot = Object.assign(
  // Top-level PlasmicRoot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    portfolio: makeNodeComponent("portfolio"),
    pfp: makeNodeComponent("pfp"),
    bluesky: makeNodeComponent("bluesky"),
    twitter: makeNodeComponent("twitter"),
    youTube: makeNodeComponent("youTube"),
    gitLab: makeNodeComponent("gitLab"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicRoot
    internalVariantProps: PlasmicRoot__VariantProps,
    internalArgProps: PlasmicRoot__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "luaily (dot) site - root",
      description:
        'hello, i\'m luaily (pronounced: "low-allie"), my new website is available at luaily.art | Prod: prod.luaily.art',
      ogImageSrc: "",
      canonical: "https://luaily.site"
    }
  }
);

export default PlasmicRoot;
/* prettier-ignore-end */
