/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wv6w1rRy2KcoypXB5fXD4W
// Component: e21xJNOnYcQi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/projectcss
import sty from "./PlasmicSwitch.module.css"; // plasmic-import: e21xJNOnYcQi/css

import CircleSvgrepoComSvgIcon from "./icons/PlasmicIcon__CircleSvgrepoComSvg"; // plasmic-import: F6Cp9X0b_Wzl/icon
import LineLSvgrepoComSvgIcon from "./icons/PlasmicIcon__LineLSvgrepoComSvg"; // plasmic-import: WdGhIz4wqxGw/icon

createPlasmicElementProxy;

export type PlasmicSwitch__VariantMembers = {
  off: "off";
  on: "on";
};
export type PlasmicSwitch__VariantsArgs = {
  off?: SingleBooleanChoiceArg<"off">;
  on?: SingleBooleanChoiceArg<"on">;
};
type VariantPropType = keyof PlasmicSwitch__VariantsArgs;
export const PlasmicSwitch__VariantProps = new Array<VariantPropType>(
  "off",
  "on"
);

export type PlasmicSwitch__ArgsType = {};
type ArgPropType = keyof PlasmicSwitch__ArgsType;
export const PlasmicSwitch__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitch__OverridesType = {
  _switch?: Flex__<"div">;
};

export interface DefaultSwitchProps {
  off?: SingleBooleanChoiceArg<"off">;
  on?: SingleBooleanChoiceArg<"on">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitch__RenderFunc(props: {
  variants: PlasmicSwitch__VariantsArgs;
  args: PlasmicSwitch__ArgsType;
  overrides: PlasmicSwitch__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "off",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.off
      },
      {
        path: "on",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.on
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"_switch"}
      data-plasmic-override={overrides._switch}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty._switch,
        {
          [sty._switchoff]: hasVariant($state, "off", "off"),
          [sty._switchon]: hasVariant($state, "on", "on")
        }
      )}
    >
      <button
        className={classNames(
          projectcss.all,
          projectcss.button,
          sty.button___97JvO,
          { [sty.buttonoff___97JvOsFfiP]: hasVariant($state, "off", "off") }
        )}
        disabled={hasVariant($state, "off", "off") ? true : false}
        onClick={async event => {
          const $steps = {};

          $steps["updateVariant"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "off",
                  operation: 4,
                  value: "off"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  $stateSet($state, vgroup, true);
                  return true;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateVariant"] != null &&
            typeof $steps["updateVariant"] === "object" &&
            typeof $steps["updateVariant"].then === "function"
          ) {
            $steps["updateVariant"] = await $steps["updateVariant"];
          }

          $steps["updateOn"] = true
            ? (() => {
                const actionArgs = { vgroup: "on", operation: 6 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  $stateSet($state, vgroup, false);
                  return false;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOn"] != null &&
            typeof $steps["updateOn"] === "object" &&
            typeof $steps["updateOn"].then === "function"
          ) {
            $steps["updateOn"] = await $steps["updateOn"];
          }
        }}
      >
        <CircleSvgrepoComSvgIcon
          className={classNames(projectcss.all, sty.svg__kfc61, {
            [sty.svgoff__kfc61SFfiP]: hasVariant($state, "off", "off"),
            [sty.svgon__kfc61MH4Bw]: hasVariant($state, "on", "on")
          })}
          role={"img"}
        />
      </button>
      <button
        className={classNames(
          projectcss.all,
          projectcss.button,
          sty.button__kn2Uq,
          { [sty.buttonon__kn2UQmH4Bw]: hasVariant($state, "on", "on") }
        )}
        disabled={hasVariant($state, "on", "on") ? true : false}
        onClick={async event => {
          const $steps = {};

          $steps["updateOn"] = true
            ? (() => {
                const actionArgs = { vgroup: "on", operation: 4 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  $stateSet($state, vgroup, true);
                  return true;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOn"] != null &&
            typeof $steps["updateOn"] === "object" &&
            typeof $steps["updateOn"].then === "function"
          ) {
            $steps["updateOn"] = await $steps["updateOn"];
          }

          $steps["updateOff"] = true
            ? (() => {
                const actionArgs = { vgroup: "off", operation: 6 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  $stateSet($state, vgroup, false);
                  return false;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOff"] != null &&
            typeof $steps["updateOff"] === "object" &&
            typeof $steps["updateOff"].then === "function"
          ) {
            $steps["updateOff"] = await $steps["updateOff"];
          }
        }}
      >
        <LineLSvgrepoComSvgIcon
          className={classNames(projectcss.all, sty.svg__efaAa, {
            [sty.svgoff__efaAasFfiP]: hasVariant($state, "off", "off"),
            [sty.svgon__efaAamH4Bw]: hasVariant($state, "on", "on")
          })}
          role={"img"}
        />
      </button>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  _switch: ["_switch"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  _switch: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitch__VariantsArgs;
    args?: PlasmicSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitch__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitch__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitch__ArgProps,
          internalVariantPropNames: PlasmicSwitch__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitch__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "_switch") {
    func.displayName = "PlasmicSwitch";
  } else {
    func.displayName = `PlasmicSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitch = Object.assign(
  // Top-level PlasmicSwitch renders the root element
  makeNodeComponent("_switch"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitch
    internalVariantProps: PlasmicSwitch__VariantProps,
    internalArgProps: PlasmicSwitch__ArgProps
  }
);

export default PlasmicSwitch;
/* prettier-ignore-end */
