/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wv6w1rRy2KcoypXB5fXD4W
// Component: rzlrD_m_Uppj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: wv6w1rRy2KcoypXB5fXD4W/projectcss
import sty from "./PlasmicSwitchThemeCarbon.module.css"; // plasmic-import: rzlrD_m_Uppj/css

import CircleSvgrepoComSvgIcon from "./icons/PlasmicIcon__CircleSvgrepoComSvg"; // plasmic-import: F6Cp9X0b_Wzl/icon
import LineLSvgrepoComSvgIcon from "./icons/PlasmicIcon__LineLSvgrepoComSvg"; // plasmic-import: WdGhIz4wqxGw/icon

createPlasmicElementProxy;

export type PlasmicSwitchThemeCarbon__VariantMembers = {
  off: "off";
  on: "on";
};
export type PlasmicSwitchThemeCarbon__VariantsArgs = {
  off?: SingleBooleanChoiceArg<"off">;
  on?: SingleBooleanChoiceArg<"on">;
};
type VariantPropType = keyof PlasmicSwitchThemeCarbon__VariantsArgs;
export const PlasmicSwitchThemeCarbon__VariantProps =
  new Array<VariantPropType>("off", "on");

export type PlasmicSwitchThemeCarbon__ArgsType = {
  onSakuraChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicSwitchThemeCarbon__ArgsType;
export const PlasmicSwitchThemeCarbon__ArgProps = new Array<ArgPropType>(
  "onSakuraChange"
);

export type PlasmicSwitchThemeCarbon__OverridesType = {
  _switch?: Flex__<"button">;
};

export interface DefaultSwitchThemeCarbonProps {
  onSakuraChange?: (val: string) => void;
  off?: SingleBooleanChoiceArg<"off">;
  on?: SingleBooleanChoiceArg<"on">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchThemeCarbon__RenderFunc(props: {
  variants: PlasmicSwitchThemeCarbon__VariantsArgs;
  args: PlasmicSwitchThemeCarbon__ArgsType;
  overrides: PlasmicSwitchThemeCarbon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "off",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.off
      },
      {
        path: "on",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.on
      },
      {
        path: "sakura",
        type: "readonly",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        onChangeProp: "onSakuraChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <button
      data-plasmic-name={"_switch"}
      data-plasmic-override={overrides._switch}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty._switch,
        {
          [sty._switchoff]: hasVariant($state, "off", "off"),
          [sty._switchon]: hasVariant($state, "on", "on")
        }
      )}
      onClick={async event => {
        const $steps = {};
      }}
      ref={ref => {
        $refs["_switch"] = ref;
      }}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__ywp0S, {
          [sty.freeBoxoff__ywp0Sopsk1]: hasVariant($state, "off", "off"),
          [sty.freeBoxon__ywp0SYr3Rj]: hasVariant($state, "on", "on")
        })}
      >
        <CircleSvgrepoComSvgIcon
          className={classNames(projectcss.all, sty.svg__b1Rnz, {
            [sty.svgoff__b1RnZopsk1]: hasVariant($state, "off", "off"),
            [sty.svgon__b1RnzYr3Rj]: hasVariant($state, "on", "on")
          })}
          role={"img"}
        />
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox___5DiiC, {
          [sty.freeBoxoff___5DiiCopsk1]: hasVariant($state, "off", "off"),
          [sty.freeBoxon___5DiiCYr3Rj]: hasVariant($state, "on", "on")
        })}
      >
        <LineLSvgrepoComSvgIcon
          className={classNames(projectcss.all, sty.svg__eIm5O, {
            [sty.svgoff__eIm5Oopsk1]: hasVariant($state, "off", "off"),
            [sty.svgon__eIm5OYr3Rj]: hasVariant($state, "on", "on")
          })}
          role={"img"}
        />
      </div>
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  _switch: ["_switch"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  _switch: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchThemeCarbon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchThemeCarbon__VariantsArgs;
    args?: PlasmicSwitchThemeCarbon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchThemeCarbon__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchThemeCarbon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchThemeCarbon__ArgProps,
          internalVariantPropNames: PlasmicSwitchThemeCarbon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchThemeCarbon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "_switch") {
    func.displayName = "PlasmicSwitchThemeCarbon";
  } else {
    func.displayName = `PlasmicSwitchThemeCarbon.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchThemeCarbon = Object.assign(
  // Top-level PlasmicSwitchThemeCarbon renders the root element
  makeNodeComponent("_switch"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitchThemeCarbon
    internalVariantProps: PlasmicSwitchThemeCarbon__VariantProps,
    internalArgProps: PlasmicSwitchThemeCarbon__ArgProps
  }
);

export default PlasmicSwitchThemeCarbon;
/* prettier-ignore-end */
