/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wv6w1rRy2KcoypXB5fXD4W

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9Zg3X311DLww } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9ZG3x311dLWW/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9Zg3X311DLww
});
